language: node_js
before_deploy:
  - test $TRAVIS_TEST_RESULT = 0
  - gulp build
deploy:
  provider: heroku
  api_key:
    secure: O7qtHp5R6kCyoPljrUVe2smAjwFLUE/guhUZBAluxfcLVTKAClWE6dBlUOHej5GmXb1234F+gqaUaDvegnlxRaXuPsp/znCqcTxNFjT3MEeFOzyxghuyf2aZRsVDtt2BwZrYZmvVTJNJUQsO+48SF0CzLqSi0TfiQyM04rbQmieSuCWrK1fkgYSdIOndb+fD7n+QLxXGsFJydgt51eAq8gMJOtxy5ssurriQHo0A5zLkLFId5epChYURDMsRIxZihfzIWBy/G3CBOVWdfux0P9gzlxMUIRZwRVuYcFk/MZpFUGKwOOzhuDFXCEF8SdtKuIJC0gtTiX6ntfOXQLOlTMeCXMRYvPbcAHfMTOPSspaCCmRQXGN5R51PoNHpV5G8M7nC1DZ//m8Tb7Qk89aDTI6ajW66zXjDDZPkf84KT4g5LpRD48eYuVVCDBQyxHbvV45x21C2EdvBwg0ZOMPY62pSZXo0Vxr72CyZ3NUo6LQcuYBJezmYQ+7USi6V69zqXlHRt35WiccBx3xpFfv+/qcOt4PbscJ9kZOG3XSBXVtspzP+7YEqc1ASkHBNLTh6DFEdNynwdOuSidLJsWiTJH7b++h3rD9mQuQaujnJB5Iljm/liUXVL4c047Sw3fgpDDlcIFsXp3GdNy9ZUfCCehRNZjpjdqqc7ksX5veHUEs=
